# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Docker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='Cname',
            field=models.ForeignKey(max_length=128, on_delete=django.db.models.deletion.CASCADE, to='Docker.Name_pass'),
        ),
    ]
