# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-27 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='c_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='container',
            name='image_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
